version: '3.4'

services:
  eventodb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  usuariodb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  pagamentodb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  ingressodb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  fiap.ingresso.evento.api:
    image: ${DOCKER_REGISTRY-}fiapingressoeventoapi
    build:
      context: .
      dockerfile: src/servicos/Fiap.Ingresso.Evento.API/Dockerfile

  fiap.ingresso.usuario.api:
    image: ${DOCKER_REGISTRY-}fiapingressousuarioapi
    build:
      context: . 
      dockerfile: src/servicos/Fiap.Ingresso.Usuario.API/Dockerfile

  fiap.ingresso.pagamento.api:
    image: ${DOCKER_REGISTRY-}fiapingressopagamentoapi
    build:
      context: .
      dockerfile: Fiap.Ingresso.Pagamento.API/Dockerfile

  fiap.ingresso.ingresso.api:
    image: ${DOCKER_REGISTRY-}fiapingressousuarioapi
    build:
      context: . 
      dockerfile: src/servicos/Fiap.Ingresso.Ingresso.API/Dockerfile

volumes:
  eventodb:
  usuariodb:  