apiVersion: v1
kind: Service
metadata:
  name: fiap-ingresso-usuario-api
spec:
  selector:
    app: fiap-ingresso-usuario-api
  ports:
  - name: usuario-api-port
    protocol: TCP
    port: 8065
    targetPort: 80
  type: LoadBalancer
