apiVersion: v1
kind: Service
metadata:
  name: fiap-ingresso-evento-api
spec:
  selector:
    app: fiap-ingresso-evento-api
  ports:
  - name: evento-api-port
    protocol: TCP
    port: 8066
    targetPort: 80
  type: LoadBalancer
