apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingressodb
spec:
  selector:
    matchLabels:
      app: ingressodb
  replicas: 1
  template:
    metadata:
      labels:
        app: ingressodb
    spec:
      containers:
      - name: ingressodb
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
        - name: SA_PASSWORD
          value: "Sw##N12345678"
        - name: ACCEPT_EULA
          value: "Y"
        ports:
        - containerPort: 1433
